import cors from "cors";
import cookieParser from "cookie-parser";
import authRoutes from "./src/routes/auth.routes.js";
import userRoutes from "./src/routes/user.routes.js";
import messageRoutes from "./src/routes/message.routes.js";
import groupRoutes from "./src/routes/group.routes.js";
import converstationRoutes from "./src/routes/converstation.routes.js";
import morgan from "morgan";
import helmet from "helmet";
import compression from "compression";
import express from "express";
import { configCORS } from "./src/config/configCORS.js";
const app = express();
configCORS(app);
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cors());
app.use(cookieParser());
app.use(morgan("dev"));
app.use(helmet());
app.use(compression());
app.use("/api/auth", authRoutes);
app.use("/api/", userRoutes);
app.use("/api/", messageRoutes);
app.use("/api/group/", groupRoutes);
app.use("/api/conversation/", converstationRoutes);

// export default app;
export default app;
